const fs=require('node:fs'),vm=require('node:vm'),crypto=require('node:crypto'),assert=require('node:assert/strict'),path=require('node:path');
const tables=new Map(),props=new Map([['SPREADSHEET_ID','test'],['PORTAL_SECRET','ab'.repeat(32)]]),mails=[];let mailFails=false,lockBusy=false;
class Sheet{
 constructor(name){this.name=name;this.values=[];}
 getLastRow(){return this.values.length;}
 getLastColumn(){return Math.max(0,...this.values.map(r=>r.length));}
 getDataRange(){return {getValues:()=>this.values.length?this.values.map(r=>r.slice()):[['']]};}
 appendRow(v){this.values.push(v.slice());}
 deleteRow(n){this.values.splice(n-1,1);}
 getRange(row,col,height=1,width=1){return {getValues:()=>Array.from({length:height},(_,i)=>Array.from({length:width},(_,j)=>this.values[row-1+i]?.[col-1+j]??'')),setValues:v=>{for(let i=0;i<height;i++){this.values[row-1+i]??=[];for(let j=0;j<width;j++){let value=v[i][j];if(typeof value==='string'&&value.startsWith("'"))value=value.slice(1);this.values[row-1+i][col-1+j]=value;}}},clearContent:()=>{for(let i=0;i<height;i++)for(let j=0;j<width;j++)this.values[row-1+i][col-1+j]='';}};}
}
const ss={getSheetByName:n=>tables.get(n),insertSheet:n=>{const s=new Sheet(n);tables.set(n,s);return s;}};
const ctx=vm.createContext({console,Date,PortalCrypto:undefined,PropertiesService:{getScriptProperties:()=>({getProperty:k=>props.get(k)||null,setProperty:(k,v)=>props.set(k,v)})},SpreadsheetApp:{openById:()=>ss},Utilities:{getUuid:()=>crypto.randomUUID(),computeHmacSha256Signature:(v,k)=>[...crypto.createHmac('sha256',k).update(v).digest()],computeDigest:(_,v)=>[...crypto.createHash('sha256').update(v).digest()],DigestAlgorithm:{SHA_256:'sha256'},newBlob:(content,type,name)=>({content,type,name})},MailApp:{getRemainingDailyQuota:()=>100,sendEmail:obj=>{if(mailFails)throw Error('mail outage');mails.push(obj);}},LockService:{getScriptLock:()=>({tryLock:()=>!lockBusy,waitLock(){},releaseLock(){}})},ContentService:{MimeType:{JSON:'json'},createTextOutput:value=>({value,setMimeType(){return this;}})}});
for(const file of ['Crypto.gs','Code.gs'])vm.runInContext(fs.readFileSync(path.join(__dirname,'../backend',file),'utf8'),ctx);
function api(action,b={}){return JSON.parse(ctx.doPost({postData:{contents:JSON.stringify({...b,action})}}).value);}
function seedUser(username,role='user',status='active'){ctx.put_('Users',{username,email:username+'@example.test',role,status,display_name:username,password_hash:'legacy',salt:'salt'});}
function session(username){const raw=crypto.randomBytes(32).toString('hex');ctx.put_('Sessions',{username,session_token:ctx.digest_(raw),device_id:'device',created_at:new Date(),last_active:new Date()});return raw;}
let passed=0;function test(name,fn){fn();passed++;console.log('PASS',name);}
ctx.migratePortal();seedUser('admin','admin');seedUser('alice');seedUser('bob');seedUser('pending','user','pending');
const admin=session('admin'),alice=session('alice'),bob=session('bob');
test('migration preserves users and is idempotent',()=>{ctx.migratePortal();assert.equal(ctx.rows_('Users').length,4);assert.equal(ctx.rows_('Services').length,2);assert.equal(ctx.rows_('Sessions').length,3);});
test('server ignores forged client role',()=>assert.equal(api('adminData',{sessionToken:alice,role:'admin'}).error,'FORBIDDEN'));
test('default deny and admin full catalogue',()=>{assert.equal(api('getPortal',{sessionToken:alice}).services.length,0);assert.equal(api('getPortal',{sessionToken:admin}).services.length,2);});
test('unauthenticated mutation denied',()=>assert.equal(api('saveAccess',{targetUsername:'alice',mode:'all',serviceIds:[],version:1}).error,'UNAUTHORIZED'));
test('selected grants enforced including direct endpoint',()=>{assert.equal(api('saveAccess',{sessionToken:admin,targetUsername:'alice',mode:'selected',serviceIds:['media'],version:1}).success,true);assert.equal(api('getPortal',{sessionToken:alice}).services.length,1);assert.equal(api('checkService',{sessionToken:alice,serviceId:'survey'}).error,'FORBIDDEN');assert.equal(api('checkServicePath',{sessionToken:alice,path:'service-survey.html'}).error,'FORBIDDEN');});
test('stale version cannot overwrite grants',()=>assert.equal(api('saveAccess',{sessionToken:admin,targetUsername:'alice',mode:'all',serviceIds:[],version:1}).error,'CONFLICT'));
test('all mode includes future services',()=>{assert.equal(api('saveAccess',{sessionToken:admin,targetUsername:'bob',mode:'all',serviceIds:[],version:1}).success,true);assert.equal(api('saveService',{sessionToken:admin,service:{id:'future',name:'Future',description:'',path:'future.html',icon:'folder',enabled:true,sort_order:3,version:0}}).success,true);assert.equal(api('getPortal',{sessionToken:bob}).services.length,3);assert.equal(api('getPortal',{sessionToken:alice}).services.length,1);});
test('URL traversal and script schemes rejected',()=>{for(const path of ['../secret.html','https://evil.test/x.html','javascript:alert(1)','//evil/x.html','x%2f.html','admin.html'])assert.equal(ctx.validPath_(path),false);});
test('disabled service denied even to admins',()=>{const s=ctx.rows_('Services').find(s=>s.id==='media');ctx.put_('Services',{...s,enabled:false});assert.equal(api('checkService',{sessionToken:alice,serviceId:'media'}).error,'FORBIDDEN');assert.equal(api('checkService',{sessionToken:admin,serviceId:'media'}).error,'FORBIDDEN');ctx.put_('Services',{...s,enabled:true});});
test('expired heartbeat cannot revive a session',()=>{const s=ctx.rows_('Sessions').find(s=>s.username==='bob');ctx.put_('Sessions',{...s,last_active:new Date(Date.now()-16*60000)});assert.equal(api('heartbeat',{sessionToken:bob,active:true}).error,'SESSION_EXPIRED');});
test('passive heartbeat does not extend idle expiry',()=>{const s=ctx.rows_('Sessions').find(s=>s.username==='alice'),before=+s.last_active;assert.equal(api('heartbeat',{sessionToken:alice,active:false}).valid,true);assert.equal(+ctx.rows_('Sessions').find(s=>s.username==='alice').last_active,before);});
test('pending users cannot log in',()=>assert.equal(api('login',{username:'pending',password:'anything',deviceId:'d'}).error,'INVALID_CREDENTIALS'));
test('reset response does not reveal account existence',()=>{const a=api('forgotPassword',{email:'alice@example.test'}),b=api('forgotPassword',{email:'missing@example.test'});assert.deepEqual(a,b);});
test('email body and subject contain no code',()=>{const m=mails.at(-1),code=m.attachments[0].content.split('\n\n')[1];assert.ok(code.length>=24);assert.ok(!m.body.includes(code));assert.ok(!m.subject.includes(code));assert.equal(m.attachments[0].name,'PR-Portal-access.txt');assert.equal(ctx.user_('alice').password_hash,'legacy');});
test('mail failure retains password and prior challenge',()=>{const old=ctx.rows_('Challenges').find(c=>c.username==='alice'&&c.kind==='reset').digest;mailFails=true;assert.equal(api('forgotPassword',{email:'alice@example.test'}).success,true);assert.equal(ctx.rows_('Challenges').find(c=>c.username==='alice'&&c.kind==='reset').digest,old);assert.equal(ctx.user_('alice').password_hash,'legacy');mailFails=false;});
test('PBKDF2 agrees with Node for UTF8 and iterations',()=>{const salt='12'.repeat(16);for(const n of [1,2,200])assert.equal(ctx.pbkdf_('ทดสอบ🔐password',salt,n),crypto.pbkdf2Sync('ทดสอบ🔐password',Buffer.from(salt,'hex'),n,32,'sha256').toString('hex'));});
test('password policy and incorrect reset do not change account',()=>{const before=ctx.user_('alice').password_hash;assert.equal(api('resetPassword',{email:'alice@example.test',temporaryPassword:'wrong',newPassword:'long enough password'}).error,'CODE_INVALID');assert.equal(ctx.user_('alice').password_hash,before);});
test('valid temporary password resets and revokes all sessions',()=>{const code=mails.find(m=>m.to==='alice@example.test').attachments[0].content.split('\n\n')[1];const start=Date.now();const r=api('resetPassword',{email:'alice@example.test',temporaryPassword:code,newPassword:'correct horse battery staple'});assert.equal(r.success,true);console.log('  PBKDF2 600000 runtime (Node VM):',Date.now()-start,'ms');assert.equal(ctx.rows_('Sessions').filter(s=>s.username==='alice').length,0);assert.equal(api('resetPassword',{email:'alice@example.test',temporaryPassword:code,newPassword:'another long password'}).error,'CODE_INVALID');});
test('new password can login; OTP device bound and one time',()=>{const r=api('login',{username:'alice',password:'correct horse battery staple',deviceId:'device'});assert.equal(r.success,true);const code=mails.at(-1).attachments[0].content.split('\n\n')[1];assert.equal(api('verifyOTP',{username:'alice',otp:code,deviceId:'other',challengeId:r.challengeId}).error,'CODE_INVALID');const good=api('verifyOTP',{username:'alice',otp:code,deviceId:'device',challengeId:r.challengeId});assert.equal(good.success,true);assert.equal(api('getPortal',{sessionToken:good.sessionToken}).success,true);assert.equal(api('verifyOTP',{username:'alice',otp:code,deviceId:'device',challengeId:r.challengeId}).error,'CODE_INVALID');});
test('OTP attempts capped at five',()=>{const id=ctx.issue_(ctx.user_('bob'),'otp','d'),code=mails.at(-1).attachments[0].content.split('\n\n')[1];for(let i=0;i<5;i++)assert.equal(api('verifyOTP',{username:'bob',otp:'wrong',deviceId:'d',challengeId:id}).error,'CODE_INVALID');assert.equal(api('verifyOTP',{username:'bob',otp:code,deviceId:'d',challengeId:id}).error,'CODE_INVALID');});
test('blocked OTP login cannot enable disabled user',()=>{const id=ctx.issue_(ctx.user_('bob'),'otp','d'),code=mails.at(-1).attachments[0].content.split('\n\n')[1];ctx.put_('Users',{...ctx.user_('bob'),status:'disabled'});assert.equal(api('verifyOTP',{username:'bob',otp:code,deviceId:'d',challengeId:id}).error,'CODE_INVALID');});
test('lock contention returns BUSY and no write',()=>{lockBusy=true;assert.equal(api('requestAccess',{}).error,'BUSY');lockBusy=false;});
test('malformed input does not disclose stack traces',()=>assert.equal(JSON.parse(ctx.doPost({postData:{contents:'{'}}).value).error,'SERVER_ERROR'));
test('unauthenticated catalogue read rejected',()=>assert.equal(api('getPortal',{}).error,'UNAUTHORIZED'));
test('temporary code cannot bypass password policy',()=>{ctx.issue_(ctx.user_('alice'),'reset','');const code=mails.at(-1).attachments[0].content.split('\n\n')[1];assert.equal(api('resetPassword',{email:'alice@example.test',temporaryPassword:code,newPassword:'short'}).error,'PASSWORD_POLICY');});
test('expired temporary password is rejected',()=>{const c=ctx.rows_('Challenges').find(c=>c.username==='alice'&&c.kind==='reset'),code=mails.at(-1).attachments[0].content.split('\n\n')[1];ctx.put_('Challenges',{...c,expires:new Date(Date.now()-1)});assert.equal(api('resetPassword',{email:'alice@example.test',temporaryPassword:code,newPassword:'a sufficiently long passphrase'}).error,'CODE_INVALID');});
test('approval applies selected grants and sends initial reset',()=>{const r=api('approveRequest',{sessionToken:admin,targetUsername:'pending',mode:'selected',serviceIds:['survey'],version:1});assert.equal(r.success,true);assert.equal(ctx.user_('pending').status,'active');assert.deepEqual(JSON.parse(ctx.access_(ctx.user_('pending')).service_ids),['survey']);assert.equal(mails.at(-1).to,'pending@example.test');});
test('malformed session timestamps fail closed',()=>{const t=session('pending'),s=ctx.rows_('Sessions').find(s=>s.username==='pending');ctx.put_('Sessions',{...s,last_active:'invalid date'});assert.equal(api('checkSession',{sessionToken:t}).error,'SESSION_EXPIRED');});
console.log('TOTAL',passed,'passed. No live Google services called.');
