const UI={
  el:(tag,attrs={},children=[])=>{const e=document.createElement(tag);for(const[k,v]of Object.entries(attrs)){if(k==='text')e.textContent=v;else if(k==='class')e.className=v;else if(k.startsWith('on'))e.addEventListener(k.slice(2),v);else if(v!==false&&v!=null)e.setAttribute(k,v===true?'':v);}for(const c of children)e.append(c);return e;},
  message(text,error=false){const e=document.getElementById('message');e.textContent=text;e.className='message '+(error?'error':'');e.hidden=!text;},
  error(r){const messages={NETWORK_ERROR:'การเชื่อมต่อขัดข้อง หากเพิ่งบันทึก กรุณาโหลดข้อมูลใหม่เพื่อตรวจผลก่อนส่งซ้ำ',BUSY:'ระบบกำลังทำรายการอื่น กรุณารอสักครู่แล้วลองใหม่',FORBIDDEN:'คุณไม่มีสิทธิ์ทำรายการนี้',UNAUTHORIZED:'กรุณาเข้าสู่ระบบใหม่',SESSION_EXPIRED:'เซสชันหมดอายุ กรุณาเข้าสู่ระบบใหม่',CONFLICT:'ข้อมูลถูกแก้ไขจากอีกหน้าจอแล้ว กรุณาโหลดข้อมูลใหม่',INVALID_CREDENTIALS:'ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง',ACCOUNT_LOCKED:'ลองเข้าสู่ระบบครบจำนวนแล้ว กรุณารอ 30 นาที',RATE_LIMITED:'ทำรายการบ่อยเกินไป กรุณารอแล้วลองใหม่',CODE_INVALID:'รหัสไม่ถูกต้อง หมดอายุ หรือใช้ครบจำนวนครั้งแล้ว',PASSWORD_POLICY:'ใช้รหัสผ่านใหม่ 15–128 ตัวอักษร',PASSWORD_RESET_REQUIRED:'บัญชีเดิมต้องตั้งรหัสผ่านใหม่หนึ่งครั้ง กรุณากดลืมรหัสผ่าน',MAIL_UNAVAILABLE:'ส่งอีเมลไม่สำเร็จ กรุณาลองใหม่หรือติดต่อผู้ดูแล',SETUP_REQUIRED:'ระบบหลังบ้านยังตั้งค่าไม่ครบ กรุณาติดต่อผู้ดูแล',DUPLICATE_PATH:'ไฟล์นี้เชื่อมกับบริการอื่นแล้ว',INVALID_INPUT:'กรุณาตรวจข้อมูลที่กรอก'};UI.message(messages[r.error]||'ทำรายการไม่สำเร็จ กรุณาลองใหม่',true);},
  async busy(button,fn){if(button.disabled)return;button.disabled=true;const t=button.textContent;button.textContent='กำลังดำเนินการ…';try{await fn();}catch{UI.message('เกิดข้อผิดพลาด กรุณาโหลดหน้าใหม่',true);}finally{button.disabled=false;button.textContent=t;}},
  icon(name){const paths={media:'M4 6h16v12H4z M9 10l6 3-6 3z',survey:'M7 4h10v17H7z M9 8h6 M9 12h6 M9 16h4',document:'M7 3h7l4 4v14H7z M14 3v5h4 M10 12h5 M10 16h5',calendar:'M4 6h16v15H4z M8 3v6 M16 3v6 M4 11h16',payment:'M3 6h18v13H3z M3 10h18 M6 15h4',support:'M8 9a4 4 0 1 1 6 4l-2 1v2 M12 19h.01',folder:'M3 7h7l2 2h9v11H3z M3 7V4h7l2 3',chart:'M5 20V12 M12 20V4 M19 20V8'};const s=document.createElementNS('http://www.w3.org/2000/svg','svg');s.setAttribute('viewBox','0 0 24 24');s.setAttribute('fill','none');s.setAttribute('stroke','currentColor');s.setAttribute('stroke-width','1.7');s.setAttribute('stroke-linecap','round');s.setAttribute('stroke-linejoin','round');s.setAttribute('aria-hidden','true');const p=document.createElementNS(s.namespaceURI,'path');p.setAttribute('d',paths[name]||paths.folder);s.append(p);return s;},
  profile(u){const p=document.getElementById('profile');if(!p)return;p.replaceChildren(UI.el('span',{class:'avatar',text:(u.displayName||u.username).slice(0,1)}),UI.el('span',{text:u.displayName||u.username}));},
  validPath(p){return /^(?:[a-zA-Z0-9_-]+\/)*[a-zA-Z0-9_-]+\.html$/.test(p)&&!/(^|\/)(index|login|dashboard|admin|reset-password)\.html$/i.test(p);}
};
